language: python
sudo: true
python:
  - 3.6

services:
  - postgresql


before_script:
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0


install:
  - pip install tox codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov

allow_failures:
    - env: DJANGO=2.0
