dist: xenial
language: python
sudo: false

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev

services:
  - postgresql


addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.5

env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
